package com.minhtrung.social_app.enums;

public enum AuthErrorCode {
    INVALID_CODE,
    EXPIRED_CODE,
    SESSION_NOT_FOUND,
    SESSION_REVOKED,
    SESSION_COMPROMISED,
    SESSION_MISMATCH,
    USER_NOT_FOUND,
    USER_MISMATCH,
    USER_CREDENTIALS_INVALID,
    DEVICE_MISMATCH,
    DEVICE_COOKIE_MISMATCH,
    INTERNAL_SERVER_ERROR
}
